version: '3'

services:
  web:
    restart: unless-stopped
    build:
      context: ./html5
      dockerfile: Dockerfile.prod
    command: gunicorn html5.wsgi:application --bind 0.0.0.0:8000 --limit-request-line 0
    volumes:
      - static_volume:/home/html5/web/static
    expose:
      - 8000
    env_file:
      - ./.env.prod
    depends_on:
      - db
  db:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - "33306:3306"      
    env_file:
      - ./.env.prod.db
    volumes:
      - mysqldb_data:/var/lib/mysql
  nginx:
    build: ./nginx
    restart: unless-stopped
    volumes:
      - static_volume:/home/html5/web/static
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  mysqldb_data:
  static_volume: