# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-10 11:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Articlehtml',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('xhtml5', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articlehtml',
            },
        ),
        migrations.CreateModel(
            name='Autenticado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eiud', models.CharField(blank=True, max_length=64, null=True)),
                ('eaccnum', models.CharField(blank=True, max_length=16, null=True)),
                ('eaccoid', models.CharField(blank=True, max_length=64, null=True)),
                ('urlparams', models.TextField(blank=True, null=True)),
                ('activo', models.CharField(blank=True, max_length=2, null=True)),
                ('pnombre', models.CharField(blank=True, max_length=255, null=True)),
                ('pid', models.CharField(blank=True, max_length=16, null=True)),
                ('poid', models.CharField(blank=True, max_length=64, null=True)),
                ('psexo', models.CharField(blank=True, max_length=1, null=True)),
                ('pnacimiento', models.CharField(blank=True, max_length=8, null=True)),
                ('pbarrio', models.CharField(blank=True, max_length=64, null=True)),
                ('pciudad', models.CharField(blank=True, max_length=64, null=True)),
                ('pregion', models.CharField(blank=True, max_length=64, null=True)),
                ('ppais', models.CharField(blank=True, max_length=3, null=True)),
                ('efecha', models.DateTimeField(blank=True, null=True)),
                ('eid', models.CharField(blank=True, max_length=16, null=True)),
                ('erealizadoroid', models.CharField(blank=True, max_length=64, null=True)),
                ('informetitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('informeuid', models.CharField(blank=True, max_length=64, null=True)),
                ('custodianoid', models.CharField(blank=True, max_length=64, null=True)),
                ('valoracion', models.CharField(blank=True, max_length=64, null=True)),
                ('solicituduid', models.CharField(blank=True, max_length=64, null=True)),
                ('autenticado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autenticado_set', to='html5cda.Autenticado')),
            ],
            options={
                'db_table': 'autenticado',
            },
        ),
        migrations.CreateModel(
            name='Cell',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'cell',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('displayname', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, choices=[('relation', 'relation'), ('unit', 'unit'), ('other', 'other')], max_length=8, null=True)),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='Code1',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, choices=[('relation', 'relation'), ('unit', 'unit'), ('other', 'other')], max_length=8, null=True)),
                ('text', models.CharField(blank=True, max_length=255, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'code1',
            },
        ),
        migrations.CreateModel(
            name='Code2',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_code2', to='html5cda.Code')),
                ('code1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code1')),
                ('rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_code2', to='html5cda.Code')),
            ],
            options={
                'db_table': 'code2',
            },
        ),
        migrations.CreateModel(
            name='Code3',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code_code3', to='html5cda.Code')),
                ('code2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code2')),
                ('rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rel_code3', to='html5cda.Code')),
            ],
            options={
                'db_table': 'code3',
            },
        ),
        migrations.CreateModel(
            name='Codesystem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('oid', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.CharField(blank=True, max_length=16, null=True)),
                ('shortname', models.CharField(blank=True, max_length=16, null=True)),
                ('hl7v2', models.CharField(blank=True, max_length=16, null=True)),
                ('dcm', models.CharField(blank=True, max_length=16, null=True)),
            ],
            options={
                'db_table': 'codesystem',
            },
        ),
        migrations.CreateModel(
            name='Col',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('code1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code1')),
            ],
            options={
                'db_table': 'col',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(blank=True, max_length=5, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'estudio',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('md5', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('iname', models.CharField(blank=True, max_length=255, null=True)),
                ('ioid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'firma',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header',
            },
        ),
        migrations.CreateModel(
            name='Inputattribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'inputattribute',
            },
        ),
        migrations.CreateModel(
            name='IntermediateBodyScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Body script',
                'db_table': 'bodyscript',
            },
        ),
        migrations.CreateModel(
            name='IntermediateHeadScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Head script',
                'db_table': 'headscript',
            },
        ),
        migrations.CreateModel(
            name='IntermediatePlantillaFooter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Footer')),
            ],
            options={
                'db_table': 'plantillafooter',
            },
        ),
        migrations.CreateModel(
            name='IntermediatePlantillaHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Header')),
            ],
            options={
                'db_table': 'plantillaheader',
            },
        ),
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('patología', 'patología')], max_length=9)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('xsitype', models.CharField(choices=[('ED', 'ED'), ('BN', 'BN'), ('CD', 'CD'), ('CR', 'CR'), ('INT', 'INT'), ('REAL', 'REAL'), ('TS', 'TS'), ('PQ', 'PQ')], max_length=4)),
                ('code1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code1')),
            ],
            options={
                'db_table': 'label',
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code1')),
                ('col', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Col')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Label')),
            ],
            options={
                'db_table': 'observation',
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.SmallIntegerField(blank=True, null=True)),
                ('selected', models.CharField(blank=True, choices=[(' selected="selected"', 'selected'), (' ', 'none')], default='', max_length=20)),
                ('disabled', models.CharField(blank=True, choices=[(' disabled="disabled"', 'disabled'), (' ', 'none')], default='', max_length=20)),
                ('interpretationcode', models.CharField(choices=[('B', 'B'), ('D', 'D'), ('U', 'U'), ('W', 'W'), ('<', '<'), ('>', '>'), ('A', 'A'), ('AA', 'AA'), ('HH', 'HH'), ('LL', 'LL'), ('H', 'H'), ('L', 'L'), ('N', 'N'), ('I', 'I'), ('MS', 'MS'), ('R', 'R'), ('S', 'S'), ('VS', 'VS')], default='B', max_length=2)),
                ('code1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code1', to='html5cda.Code1')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Label')),
                ('rel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='code1_rel', to='html5cda.Code1')),
            ],
            options={
                'db_table': 'option',
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('publisher', models.CharField(blank=True, max_length=64, null=True)),
                ('rights', models.CharField(blank=True, max_length=64, null=True)),
                ('licence', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('title2', models.CharField(blank=True, max_length=64, null=True)),
                ('identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('cantidadfirmas', models.IntegerField(blank=True, null=True)),
                ('urlparams', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantilla',
            },
        ),
        migrations.CreateModel(
            name='Plantillagruposldap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gdn', models.CharField(blank=True, max_length=255, null=True)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla')),
            ],
            options={
                'db_table': 'plantillagruposldap',
            },
        ),
        migrations.CreateModel(
            name='Referencerange',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ucum', models.CharField(choices=[('cm', 'cm'), ('', 'none')], default='', max_length=2)),
                ('low', models.FloatField(blank=True, null=True)),
                ('high', models.FloatField(blank=True, null=True)),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Label')),
            ],
            options={
                'db_table': 'referencerange',
            },
        ),
        migrations.CreateModel(
            name='Row',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('number', models.BigIntegerField(blank=True, null=True)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('code1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code1')),
                ('label', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Label')),
            ],
            options={
                'db_table': 'row',
            },
        ),
        migrations.CreateModel(
            name='Scriptelement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scriptelement',
            },
        ),
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('autenticado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Autenticado')),
                ('compcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sec_compcode_set', to='html5cda.Code')),
                ('seccode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'sec',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('idattribute', models.CharField(blank=True, max_length=4, null=True)),
                ('classattribute', models.CharField(blank=True, max_length=16, null=True)),
                ('selectclass', models.CharField(blank=True, max_length=16, null=True)),
                ('selectname', models.CharField(blank=True, max_length=32, null=True)),
                ('selecttitle', models.CharField(blank=True, max_length=255, null=True)),
                ('selectonchange', models.CharField(blank=True, max_length=255, null=True)),
                ('article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Articlehtml')),
                ('conceptcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='conceptcode', to='html5cda.Code')),
                ('formatcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='formatcode', to='html5cda.Code')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla')),
                ('super', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Section')),
            ],
            options={
                'db_table': 'section',
            },
        ),
        migrations.CreateModel(
            name='Selectoption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.CharField(blank=True, max_length=64, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Section')),
            ],
            options={
                'db_table': 'selectoption',
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eiud', models.CharField(blank=True, max_length=64, null=True)),
                ('eaccnum', models.CharField(blank=True, max_length=16, null=True)),
                ('eaccoid', models.CharField(blank=True, max_length=64, null=True)),
                ('urlparamsenviado', models.TextField(blank=True, null=True)),
                ('urlparamsrecibido', models.TextField(blank=True, null=True)),
                ('listoparaautenticacion', models.CharField(blank=True, max_length=2, null=True)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla')),
            ],
            options={
                'db_table': 'submit',
            },
        ),
        migrations.CreateModel(
            name='Subsec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsubsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('compcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsec_compcode_set', to='html5cda.Code')),
                ('parent_sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Sec')),
                ('subseccode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'subsec',
            },
        ),
        migrations.CreateModel(
            name='Subsubsec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsubsubsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('compcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsubsec_compcode_set', to='html5cda.Code')),
                ('parent_subsec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Subsec')),
                ('subsubseccode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'subsubsec',
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(blank=True, max_length=1, null=True)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('code1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code1')),
            ],
            options={
                'verbose_name': 'Widget Table',
                'db_table': 'table',
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('urlparams', models.TextField()),
                ('plantilla', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Valueattribute',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('content', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=32, null=True)),
                ('observation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Observation')),
            ],
            options={
                'db_table': 'valueattribute',
            },
        ),
        migrations.AddField(
            model_name='row',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Table'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='bodyscripts',
            field=models.ManyToManyField(related_name='plantilla_body', through='html5cda.IntermediateBodyScript', to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Estudio'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='footers',
            field=models.ManyToManyField(through='html5cda.IntermediatePlantillaFooter', to='html5cda.Footer'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='headers',
            field=models.ManyToManyField(through='html5cda.IntermediatePlantillaHeader', to='html5cda.Header'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='headscripts',
            field=models.ManyToManyField(related_name='plantilla_head', through='html5cda.IntermediateHeadScript', to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='observation',
            name='option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Option'),
        ),
        migrations.AddField(
            model_name='observation',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Row'),
        ),
        migrations.AddField(
            model_name='observation',
            name='sec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Sec'),
        ),
        migrations.AddField(
            model_name='observation',
            name='subsec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Subsec'),
        ),
        migrations.AddField(
            model_name='observation',
            name='subsubsec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Subsubsec'),
        ),
        migrations.AddField(
            model_name='observation',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Table'),
        ),
        migrations.AddField(
            model_name='intermediateplantillaheader',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateplantillafooter',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateheadscript',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateheadscript',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='intermediatebodyscript',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediatebodyscript',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='inputattribute',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Label'),
        ),
        migrations.AddField(
            model_name='firma',
            name='informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Submit'),
        ),
        migrations.AddField(
            model_name='firma',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='col',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Label'),
        ),
        migrations.AddField(
            model_name='col',
            name='table',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Table'),
        ),
        migrations.AlterUniqueTogether(
            name='codesystem',
            unique_together=set([('oid',)]),
        ),
        migrations.AddField(
            model_name='code',
            name='codesystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Codesystem'),
        ),
        migrations.AddField(
            model_name='code',
            name='translation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='translation_code', to='html5cda.Code'),
        ),
        migrations.AddField(
            model_name='cell',
            name='code1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code1'),
        ),
        migrations.AddField(
            model_name='cell',
            name='col',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Col'),
        ),
        migrations.AddField(
            model_name='cell',
            name='label',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Label'),
        ),
        migrations.AddField(
            model_name='cell',
            name='row',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Row'),
        ),
        migrations.AddField(
            model_name='autenticado',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Estudio'),
        ),
        migrations.AddField(
            model_name='autenticado',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantilla', to='html5cda.Plantilla'),
        ),
        migrations.CreateModel(
            name='WidgetInput',
            fields=[
            ],
            options={
                'verbose_name': 'Widget Input',
                'proxy': True,
            },
            bases=('html5cda.label',),
        ),
        migrations.CreateModel(
            name='WidgetSelect',
            fields=[
            ],
            options={
                'verbose_name': 'Widget Select',
                'proxy': True,
            },
            bases=('html5cda.label',),
        ),
    ]
