# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-12-06 11:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articlehtml',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articlehtml',
            },
        ),
        migrations.CreateModel(
            name='Autenticado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eiud', models.CharField(blank=True, max_length=64, null=True)),
                ('eaccnum', models.CharField(blank=True, max_length=16, null=True)),
                ('eaccoid', models.CharField(blank=True, max_length=64, null=True)),
                ('urlparams', models.CharField(blank=True, max_length=45, null=True)),
                ('activo', models.CharField(blank=True, max_length=2, null=True)),
                ('pnombre', models.CharField(blank=True, max_length=255, null=True)),
                ('pid', models.CharField(blank=True, max_length=16, null=True)),
                ('poid', models.CharField(blank=True, max_length=64, null=True)),
                ('psexo', models.CharField(blank=True, max_length=1, null=True)),
                ('pnacimiento', models.CharField(blank=True, max_length=8, null=True)),
                ('pbarrio', models.CharField(blank=True, max_length=64, null=True)),
                ('pciudad', models.CharField(blank=True, max_length=64, null=True)),
                ('pregion', models.CharField(blank=True, max_length=64, null=True)),
                ('ppais', models.CharField(blank=True, max_length=3, null=True)),
                ('efecha', models.DateTimeField(blank=True, null=True)),
                ('eid', models.CharField(blank=True, max_length=16, null=True)),
                ('erealizadoroid', models.CharField(blank=True, max_length=64, null=True)),
                ('informetitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('informeuid', models.CharField(blank=True, max_length=64, null=True)),
                ('custodianoid', models.CharField(blank=True, max_length=64, null=True)),
                ('valoracion', models.CharField(blank=True, max_length=64, null=True)),
                ('solicituduid', models.CharField(blank=True, max_length=64, null=True)),
                ('autenticado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autenticado_set', to='html5cda.Autenticado')),
            ],
            options={
                'db_table': 'autenticado',
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('displayname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'code',
            },
        ),
        migrations.CreateModel(
            name='Codesystem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('oid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'codesystem',
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('element', models.CharField(blank=True, max_length=16, null=True)),
                ('elementclasscode', models.CharField(blank=True, max_length=8, null=True)),
                ('elementmoodcode', models.CharField(blank=True, max_length=8, null=True)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('identry', models.CharField(blank=True, max_length=64, null=True)),
                ('textreferencevalue', models.CharField(blank=True, max_length=32, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'entry',
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(blank=True, max_length=5, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'estudio',
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('md5', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('udn', models.CharField(blank=True, max_length=64, null=True)),
                ('uid', models.CharField(blank=True, max_length=16, null=True)),
                ('uoid', models.CharField(blank=True, max_length=64, null=True)),
                ('uname', models.CharField(blank=True, max_length=255, null=True)),
                ('iname', models.CharField(blank=True, max_length=255, null=True)),
                ('ioid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'firma',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'footer',
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'header',
            },
        ),
        migrations.CreateModel(
            name='IntermediateBodyScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Body script',
                'db_table': 'bodyscript',
            },
        ),
        migrations.CreateModel(
            name='IntermediateHeadScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Head script',
                'db_table': 'headscript',
            },
        ),
        migrations.CreateModel(
            name='IntermediatePlantillaFooter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('footer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Footer')),
            ],
            options={
                'db_table': 'plantillafooter',
            },
        ),
        migrations.CreateModel(
            name='IntermediatePlantillaHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('header', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Header')),
            ],
            options={
                'db_table': 'plantillaheader',
            },
        ),
        migrations.CreateModel(
            name='IntermediateSecEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry')),
            ],
            options={
                'db_table': 'secentry',
            },
        ),
        migrations.CreateModel(
            name='IntermediateSubSecEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry')),
            ],
            options={
                'db_table': 'subsecentry',
            },
        ),
        migrations.CreateModel(
            name='IntermediateSubSubSecEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry')),
            ],
            options={
                'db_table': 'subsubsecentry',
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('publisher', models.CharField(blank=True, max_length=64, null=True)),
                ('rights', models.CharField(blank=True, max_length=64, null=True)),
                ('licence', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('title2', models.CharField(blank=True, max_length=64, null=True)),
                ('identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('cantidadfirmas', models.IntegerField(blank=True, null=True)),
                ('urlparams', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantilla',
            },
        ),
        migrations.CreateModel(
            name='Plantillagruposldap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gdn', models.CharField(blank=True, max_length=255, null=True)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla')),
            ],
            options={
                'db_table': 'plantillagruposldap',
            },
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('valueoriginaltext', models.CharField(blank=True, max_length=64, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry')),
            ],
            options={
                'db_table': 'qualifier',
            },
        ),
        migrations.CreateModel(
            name='Scriptelement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'scriptelement',
            },
        ),
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('autenticado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Autenticado')),
                ('compcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sec_compcode_set', to='html5cda.Code')),
                ('entries', models.ManyToManyField(through='html5cda.IntermediateSecEntry', to='html5cda.Entry')),
                ('seccode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'sec',
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idseccion', models.CharField(blank=True, max_length=4, null=True)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('templateuidroot', models.CharField(blank=True, max_length=64, null=True)),
                ('selectcolor', models.CharField(blank=True, max_length=16, null=True)),
                ('selecttitle', models.CharField(blank=True, max_length=255, null=True)),
                ('inputchecked', models.CharField(blank=True, max_length=2, null=True)),
                ('articlehtml', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Articlehtml')),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla')),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Seccion')),
            ],
            options={
                'db_table': 'seccion',
            },
        ),
        migrations.CreateModel(
            name='Selectoption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.CharField(blank=True, max_length=64, null=True)),
                ('selected', models.CharField(blank=True, max_length=2, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Seccion')),
            ],
            options={
                'db_table': 'selectoption',
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eiud', models.CharField(blank=True, max_length=64, null=True)),
                ('eaccnum', models.CharField(blank=True, max_length=16, null=True)),
                ('eaccoid', models.CharField(blank=True, max_length=64, null=True)),
                ('urlparamsenviado', models.TextField(blank=True, null=True)),
                ('urlparamsrecibido', models.TextField(blank=True, null=True)),
                ('listoparaautenticacion', models.CharField(blank=True, max_length=2, null=True)),
                ('plantilla', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla')),
            ],
            options={
                'db_table': 'submit',
            },
        ),
        migrations.CreateModel(
            name='Subsec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsubsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('compcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsec_compcode_set', to='html5cda.Code')),
                ('entries', models.ManyToManyField(through='html5cda.IntermediateSubSecEntry', to='html5cda.Entry')),
                ('parent_sec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Sec')),
                ('subseccode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'subsec',
            },
        ),
        migrations.CreateModel(
            name='Subsubsec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsubsubsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('compcode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsubsec_compcode_set', to='html5cda.Code')),
                ('entries', models.ManyToManyField(through='html5cda.IntermediateSubSubSecEntry', to='html5cda.Entry')),
                ('parent_subsec', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Subsec')),
                ('subsubseccode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
            ],
            options={
                'db_table': 'subsubsec',
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('nullflavor', models.CharField(blank=True, max_length=16, null=True)),
                ('code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Code')),
                ('entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry')),
            ],
            options={
                'db_table': 'value',
            },
        ),
        migrations.AddField(
            model_name='plantilla',
            name='bodyscripts',
            field=models.ManyToManyField(related_name='plantilla_body', through='html5cda.IntermediateBodyScript', to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Estudio'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='footers',
            field=models.ManyToManyField(through='html5cda.IntermediatePlantillaFooter', to='html5cda.Footer'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='headers',
            field=models.ManyToManyField(through='html5cda.IntermediatePlantillaHeader', to='html5cda.Header'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='headscripts',
            field=models.ManyToManyField(related_name='plantilla_head', through='html5cda.IntermediateHeadScript', to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='intermediatesubsubsecentry',
            name='subsubsec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Subsubsec'),
        ),
        migrations.AddField(
            model_name='intermediatesubsecentry',
            name='subsec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Subsec'),
        ),
        migrations.AddField(
            model_name='intermediatesecentry',
            name='sec',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Sec'),
        ),
        migrations.AddField(
            model_name='intermediateplantillaheader',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateplantillafooter',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateheadscript',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateheadscript',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='intermediatebodyscript',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediatebodyscript',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='firma',
            name='informe',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Submit'),
        ),
        migrations.AddField(
            model_name='code',
            name='codesystem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Codesystem'),
        ),
        migrations.AddField(
            model_name='autenticado',
            name='estudio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Estudio'),
        ),
        migrations.AddField(
            model_name='autenticado',
            name='plantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantilla', to='html5cda.Plantilla'),
        ),
    ]
