# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('html5cda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermediateBodyScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bodyscript',
            },
        ),
        migrations.CreateModel(
            name='IntermediateHeadScript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'headscript',
            },
        ),
        migrations.CreateModel(
            name='IntermediatePlantillaFooter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantillafooter',
            },
        ),
        migrations.CreateModel(
            name='IntermediatePlantillaHeader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantillaheader',
            },
        ),
        migrations.CreateModel(
            name='IntermediateSecEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secentry',
            },
        ),
        migrations.CreateModel(
            name='IntermediateSubSecEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsecentry',
            },
        ),
        migrations.CreateModel(
            name='IntermediateSubSubSecEntry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsubsecentry',
            },
        ),
        migrations.AlterModelOptions(
            name='articlehtml',
            options={},
        ),
        migrations.AlterModelOptions(
            name='autenticado',
            options={},
        ),
        migrations.AlterModelOptions(
            name='code',
            options={},
        ),
        migrations.AlterModelOptions(
            name='codesystem',
            options={},
        ),
        migrations.AlterModelOptions(
            name='entry',
            options={},
        ),
        migrations.AlterModelOptions(
            name='estudio',
            options={},
        ),
        migrations.AlterModelOptions(
            name='firma',
            options={},
        ),
        migrations.AlterModelOptions(
            name='footer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='header',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plantilla',
            options={},
        ),
        migrations.AlterModelOptions(
            name='plantillagruposldap',
            options={},
        ),
        migrations.AlterModelOptions(
            name='qualifier',
            options={},
        ),
        migrations.AlterModelOptions(
            name='scriptelement',
            options={},
        ),
        migrations.AlterModelOptions(
            name='sec',
            options={},
        ),
        migrations.AlterModelOptions(
            name='seccion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='selectoption',
            options={},
        ),
        migrations.AlterModelOptions(
            name='submit',
            options={},
        ),
        migrations.AlterModelOptions(
            name='susbsec',
            options={},
        ),
        migrations.AlterModelOptions(
            name='susbsubsec',
            options={},
        ),
        migrations.AlterModelOptions(
            name='value',
            options={},
        ),
        migrations.AddField(
            model_name='intermediatesubsubsecentry',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Susbsubsec'),
        ),
        migrations.AddField(
            model_name='intermediatesubsubsecentry',
            name='fkentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry'),
        ),
        migrations.AddField(
            model_name='intermediatesubsecentry',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Susbsec'),
        ),
        migrations.AddField(
            model_name='intermediatesubsecentry',
            name='fkentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry'),
        ),
        migrations.AddField(
            model_name='intermediatesecentry',
            name='fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Sec'),
        ),
        migrations.AddField(
            model_name='intermediatesecentry',
            name='fkentry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry'),
        ),
        migrations.AddField(
            model_name='intermediateplantillaheader',
            name='fkheader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Header'),
        ),
        migrations.AddField(
            model_name='intermediateplantillaheader',
            name='fkplantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateplantillafooter',
            name='fkfooter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Footer'),
        ),
        migrations.AddField(
            model_name='intermediateplantillafooter',
            name='fkplantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateheadscript',
            name='fkplantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateheadscript',
            name='fkscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='intermediatebodyscript',
            name='fkplantilla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediatebodyscript',
            name='fkscript',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Scriptelement'),
        ),
    ]
