# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-19 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('html5cda', '0004_auto_20160924_1834'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='intermediatebodyscript',
            options={'verbose_name': 'Body script'},
        ),
        migrations.AlterModelOptions(
            name='intermediateheadscript',
            options={'verbose_name': 'Head script'},
        ),
        migrations.RenameField(
            model_name='autenticado',
            old_name='fkestudio',
            new_name='estudio',
        ),
        migrations.RenameField(
            model_name='autenticado',
            old_name='fkplantilla',
            new_name='plantilla',
        ),
        migrations.RenameField(
            model_name='code',
            old_name='fkcodesystem',
            new_name='codesystem',
        ),
        migrations.RenameField(
            model_name='entry',
            old_name='fkcode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='estudio',
            old_name='fkcode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='firma',
            old_name='fkinforme',
            new_name='informe',
        ),
        migrations.RenameField(
            model_name='plantilla',
            old_name='fkestudio',
            new_name='estudio',
        ),
        migrations.RenameField(
            model_name='plantillagruposldap',
            old_name='fkplantilla',
            new_name='plantilla',
        ),
        migrations.RenameField(
            model_name='qualifier',
            old_name='fkcode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='qualifier',
            old_name='fkentry',
            new_name='entry',
        ),
        migrations.RenameField(
            model_name='sec',
            old_name='fkautenticado',
            new_name='autenticado',
        ),
        migrations.RenameField(
            model_name='sec',
            old_name='fkcompcode',
            new_name='compcode',
        ),
        migrations.RenameField(
            model_name='sec',
            old_name='fkseccode',
            new_name='seccode',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='fkarticlehtml',
            new_name='articlehtml',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='fkcode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='fkplantilla',
            new_name='plantilla',
        ),
        migrations.RenameField(
            model_name='seccion',
            old_name='fksection',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='selectoption',
            old_name='fksection',
            new_name='section',
        ),
        migrations.RenameField(
            model_name='submit',
            old_name='fkplantilla',
            new_name='plantilla',
        ),
        migrations.RenameField(
            model_name='subsec',
            old_name='fkcompcode',
            new_name='compcode',
        ),
        migrations.RenameField(
            model_name='subsec',
            old_name='fksubseccode',
            new_name='subseccode',
        ),
        migrations.RenameField(
            model_name='subsubsec',
            old_name='fkcompcode',
            new_name='compcode',
        ),
        migrations.RenameField(
            model_name='subsubsec',
            old_name='fksubsubseccode',
            new_name='subsubseccode',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='fkcode',
            new_name='code',
        ),
        migrations.RenameField(
            model_name='value',
            old_name='fkentry',
            new_name='entry',
        ),
        migrations.RemoveField(
            model_name='autenticado',
            name='fkautenticado',
        ),
        migrations.RemoveField(
            model_name='intermediatebodyscript',
            name='fkplantilla',
        ),
        migrations.RemoveField(
            model_name='intermediatebodyscript',
            name='fkscript',
        ),
        migrations.RemoveField(
            model_name='intermediateheadscript',
            name='fkplantilla',
        ),
        migrations.RemoveField(
            model_name='intermediateheadscript',
            name='fkscript',
        ),
        migrations.RemoveField(
            model_name='intermediateplantillafooter',
            name='fkfooter',
        ),
        migrations.RemoveField(
            model_name='intermediateplantillafooter',
            name='fkplantilla',
        ),
        migrations.RemoveField(
            model_name='intermediateplantillaheader',
            name='fkheader',
        ),
        migrations.RemoveField(
            model_name='intermediateplantillaheader',
            name='fkplantilla',
        ),
        migrations.RemoveField(
            model_name='intermediatesecentry',
            name='fk',
        ),
        migrations.RemoveField(
            model_name='intermediatesecentry',
            name='fkentry',
        ),
        migrations.RemoveField(
            model_name='intermediatesubsecentry',
            name='fk',
        ),
        migrations.RemoveField(
            model_name='intermediatesubsecentry',
            name='fkentry',
        ),
        migrations.RemoveField(
            model_name='intermediatesubsubsecentry',
            name='fk',
        ),
        migrations.RemoveField(
            model_name='intermediatesubsubsecentry',
            name='fkentry',
        ),
        migrations.AddField(
            model_name='autenticado',
            name='autenticado',
            field=models.ForeignKey(blank=True, db_column='fkautenticado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autenticado_set', to='html5cda.Autenticado'),
        ),
        migrations.AddField(
            model_name='intermediatebodyscript',
            name='plantilla',
            field=models.ForeignKey(blank=True, db_column='fkplantilla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediatebodyscript',
            name='script',
            field=models.ForeignKey(blank=True, db_column='fkscript', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='intermediateheadscript',
            name='plantilla',
            field=models.ForeignKey(blank=True, db_column='fkplantilla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateheadscript',
            name='script',
            field=models.ForeignKey(blank=True, db_column='fkscript', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Scriptelement'),
        ),
        migrations.AddField(
            model_name='intermediateplantillafooter',
            name='footer',
            field=models.ForeignKey(blank=True, db_column='fkfooter', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Footer'),
        ),
        migrations.AddField(
            model_name='intermediateplantillafooter',
            name='plantilla',
            field=models.ForeignKey(blank=True, db_column='fkplantilla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediateplantillaheader',
            name='header',
            field=models.ForeignKey(blank=True, db_column='fkheader', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Header'),
        ),
        migrations.AddField(
            model_name='intermediateplantillaheader',
            name='plantilla',
            field=models.ForeignKey(blank=True, db_column='fkplantilla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Plantilla'),
        ),
        migrations.AddField(
            model_name='intermediatesecentry',
            name='entry',
            field=models.ForeignKey(blank=True, db_column='fkentry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry'),
        ),
        migrations.AddField(
            model_name='intermediatesecentry',
            name='sec',
            field=models.ForeignKey(blank=True, db_column='fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Sec'),
        ),
        migrations.AddField(
            model_name='intermediatesubsecentry',
            name='entry',
            field=models.ForeignKey(blank=True, db_column='fkentry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry'),
        ),
        migrations.AddField(
            model_name='intermediatesubsecentry',
            name='subsec',
            field=models.ForeignKey(blank=True, db_column='fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Subsec'),
        ),
        migrations.AddField(
            model_name='intermediatesubsubsecentry',
            name='entry',
            field=models.ForeignKey(blank=True, db_column='fkentry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Entry'),
        ),
        migrations.AddField(
            model_name='intermediatesubsubsecentry',
            name='subsubsec',
            field=models.ForeignKey(blank=True, db_column='fk', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='html5cda.Subsubsec'),
        ),
    ]
