# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-26 17:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articlehtml',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('html', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'articlehtml',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Autenticado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eiud', models.CharField(blank=True, max_length=64, null=True)),
                ('eaccnum', models.CharField(blank=True, max_length=16, null=True)),
                ('eaccoid', models.CharField(blank=True, max_length=64, null=True)),
                ('urlparams', models.CharField(blank=True, max_length=45, null=True)),
                ('activo', models.CharField(blank=True, max_length=2, null=True)),
                ('pnombre', models.CharField(blank=True, max_length=255, null=True)),
                ('pid', models.CharField(blank=True, max_length=16, null=True)),
                ('poid', models.CharField(blank=True, max_length=64, null=True)),
                ('psexo', models.CharField(blank=True, max_length=1, null=True)),
                ('pnacimiento', models.CharField(blank=True, max_length=8, null=True)),
                ('pbarrio', models.CharField(blank=True, max_length=64, null=True)),
                ('pciudad', models.CharField(blank=True, max_length=64, null=True)),
                ('pregion', models.CharField(blank=True, max_length=64, null=True)),
                ('ppais', models.CharField(blank=True, max_length=3, null=True)),
                ('efecha', models.DateTimeField(blank=True, null=True)),
                ('eid', models.CharField(blank=True, max_length=16, null=True)),
                ('erealizadoroid', models.CharField(blank=True, max_length=64, null=True)),
                ('informetitulo', models.CharField(blank=True, max_length=255, null=True)),
                ('informeuid', models.CharField(blank=True, max_length=64, null=True)),
                ('custodianoid', models.CharField(blank=True, max_length=64, null=True)),
                ('valoracion', models.CharField(blank=True, max_length=64, null=True)),
                ('solicituduid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'autenticado',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bodyscript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bodyscript',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Code',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=16, null=True)),
                ('displayname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'code',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Codesystem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=16, null=True)),
                ('oid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'codesystem',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('element', models.CharField(blank=True, max_length=16, null=True)),
                ('elementclasscode', models.CharField(blank=True, max_length=8, null=True)),
                ('elementmoodcode', models.CharField(blank=True, max_length=8, null=True)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('identry', models.CharField(blank=True, max_length=64, null=True)),
                ('textreferencevalue', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'db_table': 'entry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Estudio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('modalidad', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'db_table': 'estudio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Firma',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('md5', models.CharField(blank=True, max_length=45, null=True)),
                ('fecha', models.DateTimeField(blank=True, null=True)),
                ('udn', models.CharField(blank=True, max_length=64, null=True)),
                ('uid', models.CharField(blank=True, max_length=16, null=True)),
                ('uoid', models.CharField(blank=True, max_length=64, null=True)),
                ('uname', models.CharField(blank=True, max_length=255, null=True)),
                ('iname', models.CharField(blank=True, max_length=255, null=True)),
                ('ioid', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'firma',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('html', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'footer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('html', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'header',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Headscript',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'headscript',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plantilla',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=64, null=True)),
                ('type', models.CharField(blank=True, max_length=64, null=True)),
                ('publisher', models.CharField(blank=True, max_length=64, null=True)),
                ('rights', models.CharField(blank=True, max_length=64, null=True)),
                ('licence', models.CharField(blank=True, max_length=64, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('creator', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(blank=True, max_length=16, null=True)),
                ('title2', models.CharField(blank=True, max_length=64, null=True)),
                ('identifier', models.CharField(blank=True, max_length=64, null=True)),
                ('cantidadfirmas', models.IntegerField(blank=True, null=True)),
                ('urlparams', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantilla',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plantillafooter',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantillafooter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plantillagruposldap',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('gdn', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'plantillagruposldap',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Plantillaheader',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'plantillaheader',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Qualifier',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('valueoriginaltext', models.CharField(blank=True, max_length=64, null=True)),
            ],
            options={
                'db_table': 'qualifier',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Scriptelement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('html', models.TextField(blank=True, null=True)),
                ('titulo', models.CharField(blank=True, max_length=64, null=True)),
                ('version', models.IntegerField(blank=True, null=True)),
                ('comentario', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'scriptelement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('idseccion', models.CharField(blank=True, max_length=4, null=True)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('templateuidroot', models.CharField(blank=True, max_length=64, null=True)),
                ('selectcolor', models.CharField(blank=True, max_length=16, null=True)),
                ('selecttitle', models.CharField(blank=True, max_length=255, null=True)),
                ('inputchecked', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'seccion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Secentry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'secentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Selectoption',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('text', models.CharField(blank=True, max_length=64, null=True)),
                ('selected', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'selectoption',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Submit',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('eiud', models.CharField(blank=True, max_length=64, null=True)),
                ('eaccnum', models.CharField(blank=True, max_length=16, null=True)),
                ('eaccoid', models.CharField(blank=True, max_length=64, null=True)),
                ('urlparamsenviado', models.TextField(blank=True, null=True)),
                ('urlparamsrecibido', models.TextField(blank=True, null=True)),
                ('listoparaautenticacion', models.CharField(blank=True, max_length=2, null=True)),
            ],
            options={
                'db_table': 'submit',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subsecentry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsecentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Subsubsecentry',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('ordinal', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'subsubsecentry',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Susbsec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsusbsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'susbsec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Susbsubsec',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('templateuid', models.CharField(blank=True, max_length=64, null=True)),
                ('idsusbsubsec', models.CharField(blank=True, max_length=4, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('text', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'susbsubsec',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(blank=True, max_length=8, null=True)),
                ('unit', models.CharField(blank=True, max_length=16, null=True)),
                ('value', models.CharField(blank=True, max_length=64, null=True)),
                ('nullflavor', models.CharField(blank=True, db_column='nullFlavor', max_length=16, null=True)),
            ],
            options={
                'db_table': 'value',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=20)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
    ]
