# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-24 18:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radiologo', '0002_auto_20160924_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='autenticado',
            name='fkautenticado',
            field=models.ForeignKey(blank=True, db_column='fkautenticado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='autenticado', to='radiologo.Autenticado'),
        ),
        migrations.AddField(
            model_name='autenticado',
            name='fkestudio',
            field=models.ForeignKey(blank=True, db_column='fkestudio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Estudio'),
        ),
        migrations.AddField(
            model_name='autenticado',
            name='fkplantilla',
            field=models.ForeignKey(blank=True, db_column='fkplantilla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='plantilla', to='radiologo.Plantilla'),
        ),
        migrations.AddField(
            model_name='code',
            name='fkcodesystem',
            field=models.ForeignKey(blank=True, db_column='fkcodesystem', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Codesystem'),
        ),
        migrations.AddField(
            model_name='entry',
            name='fkcode',
            field=models.ForeignKey(blank=True, db_column='fkcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='estudio',
            name='fkcode',
            field=models.ForeignKey(blank=True, db_column='fkcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='firma',
            name='fkinforme',
            field=models.ForeignKey(blank=True, db_column='fkinforme', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Submit'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='bodyscripts',
            field=models.ManyToManyField(related_name='plantilla_body', through='radiologo.IntermediateBodyScript', to='radiologo.Scriptelement'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='fkestudio',
            field=models.ForeignKey(blank=True, db_column='fkestudio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Estudio'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='footers',
            field=models.ManyToManyField(through='radiologo.IntermediatePlantillaFooter', to='radiologo.Footer'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='headers',
            field=models.ManyToManyField(through='radiologo.IntermediatePlantillaHeader', to='radiologo.Header'),
        ),
        migrations.AddField(
            model_name='plantilla',
            name='headscripts',
            field=models.ManyToManyField(related_name='plantilla_head', through='radiologo.IntermediateHeadScript', to='radiologo.Scriptelement'),
        ),
        migrations.AddField(
            model_name='plantillagruposldap',
            name='fkplantilla',
            field=models.ForeignKey(blank=True, db_column='fkplantilla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Plantilla'),
        ),
        migrations.AddField(
            model_name='qualifier',
            name='fkcode',
            field=models.ForeignKey(blank=True, db_column='fkcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='qualifier',
            name='fkentry',
            field=models.ForeignKey(blank=True, db_column='fkentry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Entry'),
        ),
        migrations.AddField(
            model_name='sec',
            name='entries',
            field=models.ManyToManyField(through='radiologo.IntermediateSecEntry', to='radiologo.Entry'),
        ),
        migrations.AddField(
            model_name='sec',
            name='fkautenticado',
            field=models.ForeignKey(blank=True, db_column='fkautenticado', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='secautenticado', to='radiologo.Autenticado'),
        ),
        migrations.AddField(
            model_name='sec',
            name='fkcompcode',
            field=models.ForeignKey(blank=True, db_column='fkcompcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seccompcode', to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='sec',
            name='fkseccode',
            field=models.ForeignKey(blank=True, db_column='fkseccode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='seccode', to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='fkarticlehtml',
            field=models.ForeignKey(blank=True, db_column='fkarticlehtml', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Articlehtml'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='fkcode',
            field=models.ForeignKey(blank=True, db_column='fkcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='fkplantilla',
            field=models.ForeignKey(blank=True, db_column='fkplantilla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Plantilla'),
        ),
        migrations.AddField(
            model_name='seccion',
            name='fksection',
            field=models.ForeignKey(blank=True, db_column='fksection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Seccion'),
        ),
        migrations.AddField(
            model_name='selectoption',
            name='fksection',
            field=models.ForeignKey(blank=True, db_column='fksection', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Seccion'),
        ),
        migrations.AddField(
            model_name='submit',
            name='fkplantilla',
            field=models.ForeignKey(blank=True, db_column='fkplantilla', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Plantilla'),
        ),
        migrations.AddField(
            model_name='susbsec',
            name='entries',
            field=models.ManyToManyField(through='radiologo.IntermediateSubSecEntry', to='radiologo.Entry'),
        ),
        migrations.AddField(
            model_name='susbsec',
            name='fkcompcode',
            field=models.ForeignKey(blank=True, db_column='fkcompcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fkcompcode', to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='susbsec',
            name='fksubseccode',
            field=models.ForeignKey(blank=True, db_column='fksubseccode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fksubseccode', to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='susbsec',
            name='parent_sec',
            field=models.ForeignKey(blank=True, db_column='fksec', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Sec'),
        ),
        migrations.AddField(
            model_name='susbsubsec',
            name='entries',
            field=models.ManyToManyField(through='radiologo.IntermediateSubSubSecEntry', to='radiologo.Entry'),
        ),
        migrations.AddField(
            model_name='susbsubsec',
            name='fkcompcode',
            field=models.ForeignKey(blank=True, db_column='fkcompcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='compcode', to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='susbsubsec',
            name='fksubsubseccode',
            field=models.ForeignKey(blank=True, db_column='fksubsubseccode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='subsubseccode', to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='susbsubsec',
            name='parent_subsec',
            field=models.ForeignKey(blank=True, db_column='fksubsec', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Susbsec'),
        ),
        migrations.AddField(
            model_name='value',
            name='fkcode',
            field=models.ForeignKey(blank=True, db_column='fkcode', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Code'),
        ),
        migrations.AddField(
            model_name='value',
            name='fkentry',
            field=models.ForeignKey(blank=True, db_column='fkentry', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='radiologo.Entry'),
        ),
        migrations.AlterField(
            model_name='footer',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='header',
            name='comentario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
