# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-29 19:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('html5dicom', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='role',
            unique_together=set([('name', 'user', 'service'), ('name', 'user', 'institution')]),
        ),
    ]
