# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-03 15:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html5dicom', '0002_auto_20160929_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='default',
            field=models.BooleanField(default=False),
        ),
    ]
