# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-12 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('html5dicom', '0003_role_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='max_rows',
            field=models.IntegerField(default=100),
        ),
    ]
